### ISSUE TITLE
JSON is a long type, but schema is an integer

### ISSUE THREAD

**Issue by AllenArbiter** [saasquatch/json-schema-inferrer#17]
json 
{
"int":123,
"double":123.22,
"long":12322222222222222
}

schema  
{
  "$schema" : "http://json-schema.org/draft-06/schema#",
  "type" : "object",
  "properties" : {
    "int" : {
      "type" : "integer"
    },
    "double" : {
      "type" : "number"
    },
    "long" : {
      "type" : "integer"
    }
  },
  "additionalProperties" : false,
  "required" : [ "int", "double", "long" ]
}

**Comment by slisaasquatch** [comment]
The type `long` does not exist in JSON schema. See docs [here](http://json-schema.org/understanding-json-schema/reference/type.html).
