### ISSUE TITLE
[ Feature] Is there any way to generate random data with the json schema

### ISSUE THREAD

**Issue by antstudio-git** [saasquatch/json-schema-inferrer#21]
After generated the json schema , we would to generate random fake data with it. Is there any ways of java?

**Comment by slisaasquatch** [comment]
Well, it's certainly not what this library does. Maybe take a look at [this](https://github.com/jimblackler/jsongenerator)?

**Comment by antstudio-git** [comment]
> Well, it's certainly not what this library does. Maybe take a look at [this](https://github.com/jimblackler/jsongenerator)?

awesome, bro
