### ISSUE TITLE
Can you deploy the latest version to the Maven Repository?

### ISSUE THREAD

**Issue by lcahlander** [saasquatch/json-schema-inferrer#22]
I had to clone the repository and then performed `mvn clean install` to be able to use the current version.

**Comment by slisaasquatch** [comment]
It is a valid request, but right now we are not set up for deploying to Maven Central, nor do we have plans for it. Someone seems to have deployed some previous versions to the Mulesoft Repository, but that wasn't me and I don't know who did it. I'll close the ticket for now.

**Comment by blutorange** [comment]
For what it's worth, I second this, having this available on Maven Central would be great. We had  never heard of jitpack and don't really want to add it to our infrastructure.
