### ISSUE TITLE
$ref and $id

### ISSUE THREAD

**Issue by vijay-15372** [saasquatch/json-schema-inferrer#31]
How to generate schema using $ref and $id. Seen this can be achieved using genericSchema interface. Can you share any code snippet or document to show how to use genericschema interface.

**Comment by slisaasquatch** [comment]
There are lots of implementations of `GenericSchemaFeature` within this project. For things like `$ref` and `$id`, I don't actually see how they can be generated in a reusable way, so another approach you can potentially take is simply post process the generated schema. Just a suggestion.
