### ISSUE TITLE
Build Errors.

### ISSUE THREAD

**Issue by akiransa** [saasquatch/json-schema-inferrer#32]
Description	Resource	Path	Location	Type
Missing artifact com.github.saasquatch:json-schema-inferrer:jar:0.2.0	pom.xml	/jsontojsonschema	line 17	Maven Dependency Problem
The container 'Maven Dependencies' references non existing library 'C:\dev\devtools\cache\m2_repository\com\github\saasquatch\json-schema-inferrer\0.2.0\json-schema-inferrer-0.2.0.jar'	jsontojsonschema		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	jsontojsonschema		Unknown	Java Problem

**Comment by slisaasquatch** [comment]
Did you add jitpack.io to your repositories?
https://github.com/saasquatch/json-schema-inferrer#add-the-repository

**Comment by slisaasquatch** [comment]
Closing the ticket for now. Feel free to reopen it if you still have issues.
