### ISSUE TITLE
Publish to maven central repository

### ISSUE THREAD

**Issue by kevinvincent** [saasquatch/json-schema-inferrer#4]
Hi! This is the best tool out there that converts a sample of json to json schema. Unfortunately I have a requirement that I can only use packages available in the maven central repository. Any chance you can publish it there?

**Comment by feliperandozup** [comment]
same here

**Comment by slisaasquatch** [comment]
Hi, sorry I missed the notification for this issue. At least for me, publishing to maven central is more trouble than it's worth. Do you know of an easy way of publishing to maven central?

**Comment by kevinvincent** [comment]
Hmm I don't know of a great way to publish it besides the usual long process. Would you be open to accepting a CR for the pom.xml changes?

**Comment by slisaasquatch** [comment]
Yeah let's just say I don't really have plans of doing that soon, because I never had the need for it. I guess in the meantime you can build a jar and use that? `mvn package` should just work.

**Comment by slisaasquatch** [comment]
I'll close the ticket for now because it's not something that I'm planning to do soon.
