### ISSUE TITLE
How to generate a schema with "$id" and "$ref"?

### ISSUE THREAD

**Issue by TotemGuo** [saasquatch/json-schema-inferrer#5]
Just like this article(https://json-schema.org/understanding-json-schema/structuring.html#the-id-property) says, how can i generate a schema with "$id" and "$ref"?

**Comment by zondacker** [comment]
and the other properties: allOf、oneOf、not、const、pattern、exclusiveMinimum、exclusiveMaximum、uniqueItems、if、then、else

**Comment by slisaasquatch** [comment]
Right now this library doesn't support generating `$id` and `$ref`. However, you can potentially implement your own `GenericSchemaFeature` and do it that way. @zondacker `GenericSchemaFeature` can solve some of those things.

**Comment by slisaasquatch** [comment]
I'll close the ticket for now. Personally I can't come up with a "standard" way of generating those things, and that's part of why the `GenericSchemaFeature` interface exists.
